vector_db:
  index_name: "trading-bot"

embedding_model:
  provider: "google"
  model_name: "models/embedding-001"

llm:
  provider: "google"
  model_name: "gemini-1.5-pro"

retriever:
  top_k: 3

tools:
  tavily:
    max_results: 5
